#!/usr/bin/env python

import sys
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lem = WordNetLemmatizer()

stopwords.words('english')
stopword = stopwords.words() [620:680]

for text in sys.stdin:
	words = text.split()
	for word in words:
		i = 0
		for stp in stopword:
			if stp == word:
				i = i + 1
		if i == 0:
			word = word.translate(None,string.punctuation)
			print ("%s\t%s" % (lem.lemmatize(word.lower()), 1))	
		


